routes/web.php
<?php
#-------------------------------------
#RUTAS PUBLICAS
#-------------------------------------
Auth::routes(['verify' => true]);

#Login y Deslogueo
Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login.post');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('logout', 'Auth\LoginController@logout');

#Registro de Usuario
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

# Password Reset
Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);

#Socialite o Socialogin
//Route::get('login/facebook', 'SocialiteController@redirectToProvider')->name('login.facebook');
//Route::get('login/facebook/callback', 'SocialiteController@handleProviderCallback');
//
//Route::get('login/twitter', 'SocialiteController@redirectToTwitterProvider')->name('login.twitter');
//Route::get('login/twitter/callback', 'SocialiteController@handleTwitterProviderCallback');
//
//Route::get('login/google', 'SocialiteController@redirectToGoogleProvider')->name('login.google');
//Route::get('login/google/callback', 'SocialiteController@handleGoogleProviderCallback');

#Geografico
Route::get('searchState/{pais_id}', 'EstadoController@searchState')->name('searchState');
Route::get('searchCity/{estado_id}', 'CiudadController@searchCity')->name('searchCity');

#Buscar Vendedores
Route::get('searchVendedores/{cliente_id}', 'VendedorController@searchVendedores')->name('searchVendedores');

#Buscar Datos de un Servicio
Route::get('searchServicio/{servicio_id}', 'TiposController@searchServicio')->name('searchServicio');


#--------------------------------------------------------------------------------------
#RUTAS PROTEGIDAS POR LA AUTENTICACION Y VERIFICACION DE EMAIL AL MOMENTO DEL REGISTRO
#--------------------------------------------------------------------------------------

Route::group(['middleware' => array('auth', 'verified')], function () {

    #Home
    Route::get('/dashboard', 'HomeController@dashboard')->name('home-one');

    #Rutas del Perfil
    Route::get('/perfil', 'HomeController@perfil')->name('perfil');
    Route::post('/storeperfil', 'HomeController@storeperfil')->name('storeperfil');

    #Roles
    Route::resource('roles', 'RoleController');

    #Menus
    Route::resource('menus', 'MenuController');

    #Permisos
    Route::resource('permissions', 'PermissionController');

    #Usuarios
    Route::resource('users', 'UserController');
    Route::post('users/{user}', 'UserController@cambioClave')->name('users.cambioClave');

    #Paypal
    Route::get('payment/{pricing_id}', 'PaypalController@postPayment')->name('payment');
    Route::get('payment/status/{pricing_id}', 'PaypalController@getPaymentStatus')->name('payment.status');
    Route::get('pagado/{credito_id}', 'PaypalController@pagado')->name('pagado');

    #Tipos de Servicio
    Route::resource('tipos', 'TiposController');

    #Vendedores
    Route::resource('vendedors', 'VendedorController');

    #Clientes
    Route::resource('clientes', 'ClientesController');
    Route::get('estadoFinanciero', 'ClientesController@estadoFinanciero')->name('estadoFinanciero');

    #Solicitudes
    Route::resource('solicitudes', 'SolicitudesController');

    #Tipo de Obras
    Route::resource('tipoObras', 'TipoObrasController');

    #Ordenes de Trabajo
    Route::resource('ordenes', 'OrdenesController');

    Route::resource('productos', 'ProductosController');
    Route::get('searchProductosXCategoria', 'ProductosController@searchProductosXCategoria')->name('searchProductosXCategoria');

    Route::resource('productosCategorias', 'ProductosCategoriasController');

    Route::resource('subOrden', 'SubOrdenController');
    Route::get('subOrden/listar/{orden_id}', 'SubOrdenController@listar')->name('subOrden.listar');
    Route::get('subOrden/{orden_id}', 'SubOrdenController@show')->name('subOrden.show');
    Route::get('searchXfechaXcliente/{cliente}', 'SubOrdenController@searchXfechaXcliente')->name('searchXfechaXcliente');
    Route::get('searchXfechaXclienteSinVencer/{cliente}', 'SubOrdenController@searchXfechaXclienteSinVencer')->name('searchXfechaXclienteSinVencer');
    Route::get('agenda', 'SubOrdenController@agenda')->name('agenda');
    Route::get('miagenda', 'SubOrdenController@miagenda')->name('miagenda');
    Route::get('searchAgenda/{selectMes}/{tipoId}', 'SubOrdenController@searchAgenda')->name('searchAgenda');
    Route::get('searchMyAgenda/{selectMes}/{tipoId}', 'SubOrdenController@searchMyAgenda')->name('searchMyAgenda');
    Route::get('reclamos', 'SubOrdenController@reclamos')->name('reclamos');
    Route::get('vencimientos', 'SubOrdenController@vencimientos')->name('vencimientos');

    Route::resource('subOrdenDetalle', 'SubOrdenDetalleController');


    Route::resource('autos', 'AutosController');

    Route::resource('cajas', 'CajasController');

    Route::resource('cajasProductos', 'CajasProductosController');

    Route::resource('recibos', 'RecibosController');

    Route::resource('seguimiento', 'SeguimientoController');

    Route::resource('herramientas', 'HerramientasController');

    Route::resource('convenios', 'ConveniosController');

    Route::resource('adicionalesEficiencias', 'AdicionalesEficienciaController');
    Route::get('adicionalesEficiencia', 'AdicionalesEficienciaController@adicionalesEficiencia')->name('adicionalesEficiencia');
    Route::post('guardarAdicionales', 'AdicionalesEficienciaController@guardarAdicionales')->name('guardarAdicionales');

    Route::resource('adicionalesChofers', 'AdicionalesChoferController');
    Route::get('adicionalesChofer', 'AdicionalesChoferController@adicionalesChofer')->name('adicionalesChofer');
    Route::post('guardarChofer', 'AdicionalesChoferController@guardarChofer')->name('guardarChofer');

    Route::resource('seguimientos', 'SeguimientoController');

    Route::resource('ingresosEgresos', 'IngresosEgresosController');
    Route::get('proyeccion', 'IngresosEgresosController@proyeccion')->name('proyeccion');


    /*damian */
    Route::get('mysuborders', 'SubOrdenController@mysuborders')->name('mysuborders');
    Route::get('llegadasalida', 'SeguimientoController@llegadasalida')->name('llegadasalida');
    Route::get('productividad', 'SubOrdenController@productividad')->name('productividad');
    Route::get('cuentacorriente', 'ClientesController@cuentacorriente')->name('cuentacorriente');
    Route::get('limitesfinanciacion', 'ClientesController@limitepropio')->name('limitesfinanciacion');


    Route::get('liquidar', 'LiquidacionController@liquidar')->name('rrhh.liquidar');
    Route::post('liquidacion', 'LiquidacionController@liquidacion')->name('liquidacion');
    Route::post('storeLiquidacion', 'LiquidacionController@storeLiquidacion')->name('storeLiquidacion');
    Route::resource('liquidaciones', 'LiquidacionesController');

    Route::get('clientevencimientos')->name('clientevencimientos');
    Route::get('listaprecios')->name('listaprecios');
    Route::get('###')->name('###');
    Route::get('####')->name('####');
//    Route::get('notificaciones', function(){ return "Proximamente";})->name('notificaciones');
    Route::resource('notificaciones', 'NotificacionesController');
//    Route::get('liquidacion', function(){ return "Proximamente";})->name('liquidacion');

    #Prestamos
    Route::resource('prestamos', 'PrestamosController');
});

#Correo no se quedo dormido
Route::get('nodormido/{id}', 'UserController@dormido')->name('user-dormido');



Route::resource('notificacionUsers', 'NotificacionUserController');


Route::resource('statuses', 'StatusController');



Route::resource('feriados', 'FeriadoController');


Route::resource('barrios', 'BarriosController');

resources/views/home-one.blade.php
@extends('templates.material.main')
@section('jquery') {{-- Including this section to override it empty. Using jQuery from webpack build --}} @endsection
@section('css')


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
    <link rel="stylesheet" href="/vendor/wrappixel/material-pro/4.2.1/assets/plugins/toast-master/css/jquery.toast.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.css"/>
    <link rel="stylesheet" href="{{asset('css/introjs.css')}}">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.dataTables.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">

    <style>
        .ticket {
            width: 40%;

        }

        @media only screen and (max-width: 600px) {
            .ticket {
                width: 30%;
                padding: 15px;
            }
        }

        .dtp > .dtp-content > .dtp-date-view > header.dtp-header {
            background: #1e88e5;
            color: #fff;
            text-align: center;
            padding: 0.3em;
        }

        .dtp div.dtp-date, .dtp div.dtp-time {
            background: #1e88e5;
            text-align: center;
            color: #fff;
            padding: 10px;
        }

        .dtp .p10 > a {
            color: #fff;
            text-decoration: none;
        }

        .dtp table.dtp-picker-days tr > td > a.selected {
            background: #1e88e5;
            color: #fff;
        }

        #dtp_UpXtk {
            overflow-y: inherit;
            overflow-x: hidden;
        }

        .dropzone {
            border: none;
            background: none !important;
        }

        .dropzone-style {
            border: 1px dashed #ccc;
            border-radius: 10px;
        }

        .dz-message {
            height: 70px;
        }

        table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > td:first-child:before, table.dataTable.dtr-inline.collapsed > tbody > tr[role="row"] > th:first-child:before {
            top: 15px;
            background-color: #26c6da;
        }
    </style>
@endsection
@push('before-scripts')
    <script src="{{ mix('/js/home-one.js') }}"></script>
@endpush
@section('content')

    @if(session('claveCambiada'))
        <div class="card">
            <div class="card-body">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="alert alert-success text-center">{{session('claveCambiada')}}</div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    @endif
    @if ($password_admin)
        <div class="card">
            <div class="card-body">
                @include('users.change_password')
            </div>
        </div>
    @endif
    @if ($completeData)
        <div class="card">
            <div class="card-body">
                @include('users.complete_data')
            </div>
        </div>
    @endif

    @if(in_array(4, Auth::user()->perfiles->pluck('role_id')->toArray()) || in_array(5, Auth::user()->perfiles->pluck('role_id')->toArray()) || in_array(6, Auth::user()->perfiles->pluck('role_id')->toArray()) || in_array(7, Auth::user()->perfiles->pluck('role_id')->toArray()))

        @include('flash::message')

        <div class="row">
            @foreach($subordenesDelDia AS $i=>$item)

                <div class="col-md-4">
                    <div class="card card-outline-{{$item->tipos->color}}">
                        <div class="card-header">
                            <h4 class="m-b-0 text-white">{{$item->tipos->tipo}}</h4></div>
                        <div class="card-body text-center">
                            <h2>
                                Hora de Inicio: <b>{{Carbon\Carbon::parse($item->hora_inicio)->format('g:i A')}}</b>
                            </h2>
                            <div class="row text-left">
                                <div class="col-sm-12">
                                    <b>Consumidor:</b> {{strtoupper($item->ordenes->consumidor_nombre)}}
                                </div>
                                <div class="col-sm-12">
                                    <b>Categoría:</b> {{$item->categoriasProductos->categoria}}
                                </div>
                                <div class="col-sm-12">
                                    <b>Provincia:</b> {{$item->ordenes->provincias->name}}
                                </div>
                                <div class="col-sm-12">
                                    <b>Localidad:</b> {{$item->ordenes->localidades->name}}
                                </div>
                                <div class="col-sm-12">
                                    <b>Dirección:</b> {{$item->ordenes->consumidor_address}}
                                </div>
                                <div class="col-sm-12">
                                    <b>Teléfono:</b> {{$item->ordenes->consumidor_tlf}}
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">

                            @if(!$seguimiento=\App\Models\SubOrden::searchUltSeguimiento($item->id))
                                <form action="{{route('seguimiento.store')}}" method="post" id="formSeguimiento<?=$i?>">
                                    @csrf
                                    <input type="hidden" id="latitud<?=$i?>" name="latitud" value="">
                                    <input type="hidden" id="longitud<?=$i?>" name="longitud" value="">
                                    <input type="hidden" name="suborden_id" value="{{$item->id}}">
                                    <input type="hidden" name="tipo" value="1">
                                    <button class="btn btn-success btn-block btnLlegue" type="button" data-id="<?=$i?>">
                                        <i class="fas fa-door-open fa-2x"></i>
                                        <h3 class="text-white">LLEGUE</h3>
                                    </button>
                                </form>
                            @else
                                @if(\App\Models\SubOrden::searchUltSeguimiento($item->id)=='1')
                                        <button type="button" class="btn btn-danger btn-block btnMeFui"
                                                data-target="#ModalMeFui" data-toggle="modal"
                                                data-subordenid="{{$item->id}}">
                                                <i class="fas fa-door-closed fa-2x"></i>
                                                <h3 class="text-white">ME FUI</h3>
                                        </button>
                                @else
                                    <div class="alert alert-warning">ATENDIDO</div>
                                @endif
                            @endif
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

        @include('modalSeguimiento')

    @else
        <div class="jumbotron bg-white">
            <h3 class="">Hola {{Auth::user()->nombre}}!</h3>
            <hr class="my-4">
            <p>Navega a traves de las opciones presentadas en el panel lateral izquierdo.</p>
        </div>
    @endif



@endsection

@section('js')
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/locale/es.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/dropzone.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @if(in_array(4, Auth::user()->perfiles->pluck('role_id')->toArray()) || in_array(5, Auth::user()->perfiles->pluck('role_id')->toArray()) || in_array(6, Auth::user()->perfiles->pluck('role_id')->toArray()) || in_array(7, Auth::user()->perfiles->pluck('role_id')->toArray()))
        <script>

            let latitud;
            let longitud;

        function getGeolocation() {
            navigator.geolocation.getCurrentPosition(drawMap);
        }
        function drawMap(geoPos) {
            geolocate = new google.maps.LatLng(geoPos.coords.latitude, geoPos.coords.longitude);
            latitud = geoPos.coords.latitude;
            longitud = geoPos.coords.longitude;

            console.log( 'latitud', latitud );
        }

        getGeolocation();
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyASRlQkkJPSVOJOQhgNZru739GwiVKaK9o"></script>

        <script>
            $('.btnLlegue').click(function () {
                let id=$(this).data('id');
                $('#latitud'+id).val(latitud);
                $('#longitud'+id).val(longitud);
                $('#formSeguimiento'+id).submit();
            });
        </script>
        <script>
            $('.btnMeFui').click(function () {

                $('#latitud').val(latitud);
                $('#longitud').val(longitud);
                $('#suborden_id').val($(this).data('subordenid'));
                $('#observacion').val('');
                $('#fotos').val('');
            });
        </script>
@endif


@endsection

resources/views/modalSeguimiento.blade.php
<!--/*************************************************************
**      MODAL Seguimiento Me Fui                                     **
**************************************************************/-->
<div id="ModalMeFui" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <form action="{{route('seguimiento.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Resumen de Obra</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12">
                                <table class="table table-striped table-bordered" id="tableFotos">
                                    <tbody>
                                    <tr>
                                        <td>
                                            <input type="file" name="foto[]" accept="image/png,image/jpeg,image/gif" class="form-control pb-5">
                                        </td>
                                        <td style="vertical-align: middle">
                                            <button class="btn btn-outline-danger btn-sm btnDelFoto" type="button">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="observacion">Observación:</label>
                                <textarea name="observacion" id="observacion" class="form-control"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="latitud" value="" id="latitud">
                    <input type="hidden" name="longitud" value="" id="longitud">
                    <input type="hidden" id="contadorFoto" name="contadorFoto" value="1">
                    <input type="hidden" name="suborden_id" id="suborden_id" value="">
                    <input type="hidden" name="tipo" value="2">

                    <button class="btn btn-primary" type="button" id="btnAddFoto">Agregar Otra Foto</button>
                    <button type="submit" class="btn btn-danger waves-effect text-left">Me Fui</button>
                    <button type="button" class="btn btn-success waves-effect text-left" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!--************************************************************-->

@section('scripts')
    <script src="{{asset('vendor/wrappixel/material-pro/4.2.1/assets/plugins/sweetalert/sweetalert.min.js')}}"></script>
    <script src="{{asset('js/addFotos.js')}}"></script>

@endsection