routes/web.php
<?php
#-------------------------------------
#RUTAS PUBLICAS
#-------------------------------------
Auth::routes(['verify' => true]);

#Login y Deslogueo
Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login.post');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('logout', 'Auth\LoginController@logout');

#Registro de Usuario
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

# Password Reset
Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);

#Socialite o Socialogin
//Route::get('login/facebook', 'SocialiteController@redirectToProvider')->name('login.facebook');
//Route::get('login/facebook/callback', 'SocialiteController@handleProviderCallback');
//
//Route::get('login/twitter', 'SocialiteController@redirectToTwitterProvider')->name('login.twitter');
//Route::get('login/twitter/callback', 'SocialiteController@handleTwitterProviderCallback');
//
//Route::get('login/google', 'SocialiteController@redirectToGoogleProvider')->name('login.google');
//Route::get('login/google/callback', 'SocialiteController@handleGoogleProviderCallback');

#Geografico
Route::get('searchState/{pais_id}', 'EstadoController@searchState')->name('searchState');
Route::get('searchCity/{estado_id}', 'CiudadController@searchCity')->name('searchCity');

#Buscar Vendedores
Route::get('searchVendedores/{cliente_id}', 'VendedorController@searchVendedores')->name('searchVendedores');

#Buscar Datos de un Servicio
Route::get('searchServicio/{servicio_id}', 'TiposController@searchServicio')->name('searchServicio');


#--------------------------------------------------------------------------------------
#RUTAS PROTEGIDAS POR LA AUTENTICACION Y VERIFICACION DE EMAIL AL MOMENTO DEL REGISTRO
#--------------------------------------------------------------------------------------

Route::group(['middleware' => array('auth', 'verified')], function () {

    #Home
    Route::get('/dashboard', 'HomeController@dashboard')->name('home-one');

    #Rutas del Perfil
    Route::get('/perfil', 'HomeController@perfil')->name('perfil');
    Route::post('/storeperfil', 'HomeController@storeperfil')->name('storeperfil');

    #Roles
    Route::resource('roles', 'RoleController');

    #Menus
    Route::resource('menus', 'MenuController');

    #Permisos
    Route::resource('permissions', 'PermissionController');

    #Usuarios
    Route::resource('users', 'UserController');
    Route::post('users/{user}', 'UserController@cambioClave')->name('users.cambioClave');

    #Paypal
    Route::get('payment/{pricing_id}', 'PaypalController@postPayment')->name('payment');
    Route::get('payment/status/{pricing_id}', 'PaypalController@getPaymentStatus')->name('payment.status');
    Route::get('pagado/{credito_id}', 'PaypalController@pagado')->name('pagado');

    #Tipos de Servicio
    Route::resource('tipos', 'TiposController');

    #Vendedores
    Route::resource('vendedors', 'VendedorController');

    #Clientes
    Route::resource('clientes', 'ClientesController');
    Route::get('estadoFinanciero', 'ClientesController@estadoFinanciero')->name('estadoFinanciero');

    #Solicitudes
    Route::resource('solicitudes', 'SolicitudesController');

    #Tipo de Obras
    Route::resource('tipoObras', 'TipoObrasController');

    #Ordenes de Trabajo
    Route::resource('ordenes', 'OrdenesController');

    Route::resource('productos', 'ProductosController');
    Route::get('searchProductosXCategoria', 'ProductosController@searchProductosXCategoria')->name('searchProductosXCategoria');

    Route::resource('productosCategorias', 'ProductosCategoriasController');

    Route::resource('subOrden', 'SubOrdenController');
    Route::get('subOrden/listar/{orden_id}', 'SubOrdenController@listar')->name('subOrden.listar');
    Route::get('subOrden/{orden_id}', 'SubOrdenController@show')->name('subOrden.show');
    Route::get('searchXfechaXcliente/{cliente}', 'SubOrdenController@searchXfechaXcliente')->name('searchXfechaXcliente');
    Route::get('searchXfechaXclienteSinVencer/{cliente}', 'SubOrdenController@searchXfechaXclienteSinVencer')->name('searchXfechaXclienteSinVencer');
    Route::get('agenda', 'SubOrdenController@agenda')->name('agenda');
    Route::get('miagenda', 'SubOrdenController@miagenda')->name('miagenda');
    Route::get('searchAgenda/{selectMes}/{tipoId}', 'SubOrdenController@searchAgenda')->name('searchAgenda');
    Route::get('searchMyAgenda/{selectMes}/{tipoId}', 'SubOrdenController@searchMyAgenda')->name('searchMyAgenda');
    Route::get('reclamos', 'SubOrdenController@reclamos')->name('reclamos');
    Route::get('vencimientos', 'SubOrdenController@vencimientos')->name('vencimientos');

    Route::resource('subOrdenDetalle', 'SubOrdenDetalleController');


    Route::resource('autos', 'AutosController');

    Route::resource('cajas', 'CajasController');

    Route::resource('cajasProductos', 'CajasProductosController');

    Route::resource('recibos', 'RecibosController');

    Route::resource('seguimiento', 'SeguimientoController');

    Route::resource('herramientas', 'HerramientasController');

    Route::resource('convenios', 'ConveniosController');

    Route::resource('adicionalesEficiencias', 'AdicionalesEficienciaController');
    Route::get('adicionalesEficiencia', 'AdicionalesEficienciaController@adicionalesEficiencia')->name('adicionalesEficiencia');
    Route::post('guardarAdicionales', 'AdicionalesEficienciaController@guardarAdicionales')->name('guardarAdicionales');

    Route::resource('adicionalesChofers', 'AdicionalesChoferController');
    Route::get('adicionalesChofer', 'AdicionalesChoferController@adicionalesChofer')->name('adicionalesChofer');
    Route::post('guardarChofer', 'AdicionalesChoferController@guardarChofer')->name('guardarChofer');

    Route::resource('seguimientos', 'SeguimientoController');

    Route::resource('ingresosEgresos', 'IngresosEgresosController');
    Route::get('proyeccion', 'IngresosEgresosController@proyeccion')->name('proyeccion');


    /*damian */
    Route::get('mysuborders', 'SubOrdenController@mysuborders')->name('mysuborders');
    Route::get('llegadasalida', 'SeguimientoController@llegadasalida')->name('llegadasalida');
    Route::get('productividad', 'SubOrdenController@productividad')->name('productividad');
    Route::get('cuentacorriente', 'ClientesController@cuentacorriente')->name('cuentacorriente');
    Route::get('limitesfinanciacion', 'ClientesController@limitepropio')->name('limitesfinanciacion');


    Route::get('liquidar', 'LiquidacionController@liquidar')->name('rrhh.liquidar');
    Route::post('liquidacion', 'LiquidacionController@liquidacion')->name('liquidacion');
    Route::post('storeLiquidacion', 'LiquidacionController@storeLiquidacion')->name('storeLiquidacion');
    Route::resource('liquidaciones', 'LiquidacionesController');

    Route::get('clientevencimientos')->name('clientevencimientos');
    Route::get('listaprecios')->name('listaprecios');
    Route::get('###')->name('###');
    Route::get('####')->name('####');
//    Route::get('notificaciones', function(){ return "Proximamente";})->name('notificaciones');
    Route::resource('notificaciones', 'NotificacionesController');
//    Route::get('liquidacion', function(){ return "Proximamente";})->name('liquidacion');

    #Prestamos
    Route::resource('prestamos', 'PrestamosController');
});

#Correo no se quedo dormido
Route::get('nodormido/{id}', 'UserController@dormido')->name('user-dormido');



Route::resource('notificacionUsers', 'NotificacionUserController');


Route::resource('statuses', 'StatusController');



Route::resource('feriados', 'FeriadoController');


Route::resource('barrios', 'BarriosController');

app/Models/AdicionalesEficiencia.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class AdicionalesEficiencia
 * @package App\Models
 * @version February 28, 2020, 9:53 pm EST
 *
 * @property integer convenio_id
 * @property integer minimo
 * @property integer maximo
 * @property number adicional_costo
 */
class AdicionalesEficiencia extends Model
{
    use SoftDeletes;

    public $table = 'adicionales_eficiencia';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'convenio_id',
        'minimo',
        'maximo',
        'adicional_costo'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'convenio_id' => 'integer',
        'minimo' => 'integer',
        'maximo' => 'integer',
        'adicional_costo' => 'float'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'convenio_id' => 'required',
        'minimo' => 'required',
        'maximo' => 'required',
        'adicional_costo' => 'required'
    ];

    
}

app/Http/Controllers/AdicionalesEficienciaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAdicionalesEficienciaRequest;
use App\Http\Requests\UpdateAdicionalesEficienciaRequest;
use App\Models\AdicionalesEficiencia;
use App\Models\Convenios;
use App\Repositories\AdicionalesEficienciaRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class AdicionalesEficienciaController extends AppBaseController
{
    /** @var  AdicionalesEficienciaRepository */
    private $adicionalesEficienciaRepository;

    public function __construct(AdicionalesEficienciaRepository $adicionalesEficienciaRepo)
    {
        $this->adicionalesEficienciaRepository = $adicionalesEficienciaRepo;
    }


    public function adicionalesEficiencia()
    {
        $adicionales = AdicionalesEficiencia::all();
        $convenios = Convenios::orderBy('convenio')->get();

        return view('adicionales_eficiencias.edit', compact('adicionales', 'convenios'));
    }

    /**
     * Update the specified AdicionalesEficiencia in storage.
     *
     * @param  int              $id
     * @param UpdateAdicionalesEficienciaRequest $request
     *
     * @return Response
     */
    public function guardarAdicionales(Request $request)
    {

        $datos = $request->input();

        foreach ($datos['convenio_id'] AS $i=> $convenio_id){

            $data = [
                    'convenio_id'=>$convenio_id,
                    'minimo'=>$datos['minimo'][$i],
                    'maximo'=>$datos['maximo'][$i],
                    'adicional_costo'=>$datos['adicional_costo'][$i],
            ];

            AdicionalesEficiencia::where('id', $datos['id'][$i])->update($data);

        }


        Flash::success('Adicionales Eficiencia updated successfully.');

        return redirect(route('adicionalesEficiencia'));
    }

}

resources/views/adicionales_eficiencias/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Adicionales Eficiencia
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">

                    <div class="col-sm-12">
                        @include('flash::message')
                    </div>

                    <form action="guardarAdicionales" method="post">
                        @csrf

                        @foreach($adicionales AS $adicional)
                        <div class="row">
                            <input type="hidden" name="id[]" value="{{$adicional->id}}">
                            <!-- Convenio Id Field -->
                            <div class="form-group col-sm-3 text-center">
                                <label for="convenio_id">{{ __('Convenio') }}</label>
                                <select class="form-control {{ $errors->has('convenio_id') ? ' is-invalid' : '' }}" name="convenio_id[]" id="convenio_id">
                                    <option value="">:: Seleccione ::</option>
                                    @foreach($convenios AS $convenio)
                                        <option value="{{$convenio->id}}" @isset($adicional) @if($convenio->id==$adicional->convenio_id) selected
                                                @endif @endisset @if(old('convenio_id')==$convenio->id) selected @endif>{{$convenio->convenio}}</option>
                                    @endforeach
                                </select>
                                @if ($errors->has('convenio_id'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('convenio_id') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <!-- Minimo Field -->
                            <div class="form-group col-sm-3 text-center">
                                {!! Form::label('minimo', 'Minimo:') !!}
                                {!! Form::number('minimo[]', $adicional->minimo, ['class' => 'form-control']) !!}
                            </div>

                            <!-- Maximo Field -->
                            <div class="form-group col-sm-3 text-center">
                                {!! Form::label('maximo', 'Maximo:') !!}
                                <table>
                                    <tr>
                                        <td style="font-size: xx-large" class="font-weight-bold">>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                        <td align="center">{!! Form::number('maximo[]', $adicional->maximo, ['class' => 'form-control']) !!}</td>
                                        <td style="font-size: xx-large" class="font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;<</td>
                                    </tr>
                                </table>
                            </div>

                            <!-- Adicional Costo Field -->
                            <div class="form-group col-sm-3 text-center">
                                {!! Form::label('adicional_costo', 'Adicional Costo:') !!}
                                {!! Form::number('adicional_costo[]', $adicional->adicional_costo, ['class' => 'form-control']) !!}
                            </div>


                        </div>
                        @endforeach
                            <!-- Submit Field -->
                            <div class="form-group col-sm-12">
                                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                                <a href="{{ route('adicionalesEficiencias.index') }}" class="btn btn-default">Cancel</a>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection