routes/web.php
<?php
#-------------------------------------
#RUTAS PUBLICAS
#-------------------------------------
Auth::routes(['verify' => true]);

#Login y Deslogueo
Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login.post');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('logout', 'Auth\LoginController@logout');

#Registro de Usuario
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

# Password Reset
Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);

#Socialite o Socialogin
//Route::get('login/facebook', 'SocialiteController@redirectToProvider')->name('login.facebook');
//Route::get('login/facebook/callback', 'SocialiteController@handleProviderCallback');
//
//Route::get('login/twitter', 'SocialiteController@redirectToTwitterProvider')->name('login.twitter');
//Route::get('login/twitter/callback', 'SocialiteController@handleTwitterProviderCallback');
//
//Route::get('login/google', 'SocialiteController@redirectToGoogleProvider')->name('login.google');
//Route::get('login/google/callback', 'SocialiteController@handleGoogleProviderCallback');

#Geografico
Route::get('searchState/{pais_id}', 'EstadoController@searchState')->name('searchState');
Route::get('searchCity/{estado_id}', 'CiudadController@searchCity')->name('searchCity');

#Buscar Vendedores
Route::get('searchVendedores/{cliente_id}', 'VendedorController@searchVendedores')->name('searchVendedores');

#Buscar Datos de un Servicio
Route::get('searchServicio/{servicio_id}', 'TiposController@searchServicio')->name('searchServicio');


#--------------------------------------------------------------------------------------
#RUTAS PROTEGIDAS POR LA AUTENTICACION Y VERIFICACION DE EMAIL AL MOMENTO DEL REGISTRO
#--------------------------------------------------------------------------------------

Route::group(['middleware' => array('auth', 'verified')], function () {

    #Home
    Route::get('/dashboard', 'HomeController@dashboard')->name('home-one');

    #Rutas del Perfil
    Route::get('/perfil', 'HomeController@perfil')->name('perfil');
    Route::post('/storeperfil', 'HomeController@storeperfil')->name('storeperfil');

    #Roles
    Route::resource('roles', 'RoleController');

    #Menus
    Route::resource('menus', 'MenuController');

    #Permisos
    Route::resource('permissions', 'PermissionController');

    #Usuarios
    Route::resource('users', 'UserController');
    Route::post('users/{user}', 'UserController@cambioClave')->name('users.cambioClave');

    #Paypal
    Route::get('payment/{pricing_id}', 'PaypalController@postPayment')->name('payment');
    Route::get('payment/status/{pricing_id}', 'PaypalController@getPaymentStatus')->name('payment.status');
    Route::get('pagado/{credito_id}', 'PaypalController@pagado')->name('pagado');

    #Tipos de Servicio
    Route::resource('tipos', 'TiposController');

    #Vendedores
    Route::resource('vendedors', 'VendedorController');

    #Clientes
    Route::resource('clientes', 'ClientesController');
    Route::get('estadoFinanciero', 'ClientesController@estadoFinanciero')->name('estadoFinanciero');

    #Solicitudes
    Route::resource('solicitudes', 'SolicitudesController');

    #Tipo de Obras
    Route::resource('tipoObras', 'TipoObrasController');

    #Ordenes de Trabajo
    Route::resource('ordenes', 'OrdenesController');

    Route::resource('productos', 'ProductosController');
    Route::get('searchProductosXCategoria', 'ProductosController@searchProductosXCategoria')->name('searchProductosXCategoria');

    Route::resource('productosCategorias', 'ProductosCategoriasController');

    Route::resource('subOrden', 'SubOrdenController');
    Route::get('subOrden/listar/{orden_id}', 'SubOrdenController@listar')->name('subOrden.listar');
    Route::get('subOrden/{orden_id}', 'SubOrdenController@show')->name('subOrden.show');
    Route::get('searchXfechaXcliente/{cliente}', 'SubOrdenController@searchXfechaXcliente')->name('searchXfechaXcliente');
    Route::get('searchXfechaXclienteSinVencer/{cliente}', 'SubOrdenController@searchXfechaXclienteSinVencer')->name('searchXfechaXclienteSinVencer');
    Route::get('agenda', 'SubOrdenController@agenda')->name('agenda');
    Route::get('miagenda', 'SubOrdenController@miagenda')->name('miagenda');
    Route::get('searchAgenda/{selectMes}/{tipoId}', 'SubOrdenController@searchAgenda')->name('searchAgenda');
    Route::get('searchMyAgenda/{selectMes}/{tipoId}', 'SubOrdenController@searchMyAgenda')->name('searchMyAgenda');
    Route::get('reclamos', 'SubOrdenController@reclamos')->name('reclamos');
    Route::get('vencimientos', 'SubOrdenController@vencimientos')->name('vencimientos');

    Route::resource('subOrdenDetalle', 'SubOrdenDetalleController');


    Route::resource('autos', 'AutosController');

    Route::resource('cajas', 'CajasController');

    Route::resource('cajasProductos', 'CajasProductosController');

    Route::resource('recibos', 'RecibosController');

    Route::resource('seguimiento', 'SeguimientoController');

    Route::resource('herramientas', 'HerramientasController');

    Route::resource('convenios', 'ConveniosController');

    Route::resource('adicionalesEficiencias', 'AdicionalesEficienciaController');
    Route::get('adicionalesEficiencia', 'AdicionalesEficienciaController@adicionalesEficiencia')->name('adicionalesEficiencia');
    Route::post('guardarAdicionales', 'AdicionalesEficienciaController@guardarAdicionales')->name('guardarAdicionales');

    Route::resource('adicionalesChofers', 'AdicionalesChoferController');
    Route::get('adicionalesChofer', 'AdicionalesChoferController@adicionalesChofer')->name('adicionalesChofer');
    Route::post('guardarChofer', 'AdicionalesChoferController@guardarChofer')->name('guardarChofer');

    Route::resource('seguimientos', 'SeguimientoController');

    Route::resource('ingresosEgresos', 'IngresosEgresosController');
    Route::get('proyeccion', 'IngresosEgresosController@proyeccion')->name('proyeccion');


    /*damian */
    Route::get('mysuborders', 'SubOrdenController@mysuborders')->name('mysuborders');
    Route::get('llegadasalida', 'SeguimientoController@llegadasalida')->name('llegadasalida');
    Route::get('productividad', 'SubOrdenController@productividad')->name('productividad');
    Route::get('cuentacorriente', 'ClientesController@cuentacorriente')->name('cuentacorriente');
    Route::get('limitesfinanciacion', 'ClientesController@limitepropio')->name('limitesfinanciacion');


    Route::get('liquidar', 'LiquidacionController@liquidar')->name('rrhh.liquidar');
    Route::post('liquidacion', 'LiquidacionController@liquidacion')->name('liquidacion');
    Route::post('storeLiquidacion', 'LiquidacionController@storeLiquidacion')->name('storeLiquidacion');
    Route::resource('liquidaciones', 'LiquidacionesController');

    Route::get('clientevencimientos')->name('clientevencimientos');
    Route::get('listaprecios')->name('listaprecios');
    Route::get('###')->name('###');
    Route::get('####')->name('####');
//    Route::get('notificaciones', function(){ return "Proximamente";})->name('notificaciones');
    Route::resource('notificaciones', 'NotificacionesController');
//    Route::get('liquidacion', function(){ return "Proximamente";})->name('liquidacion');

    #Prestamos
    Route::resource('prestamos', 'PrestamosController');
});

#Correo no se quedo dormido
Route::get('nodormido/{id}', 'UserController@dormido')->name('user-dormido');



Route::resource('notificacionUsers', 'NotificacionUserController');


Route::resource('statuses', 'StatusController');



Route::resource('feriados', 'FeriadoController');


Route::resource('barrios', 'BarriosController');

app/Models/TipoObras.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class TipoObras
 * @package App\Models
 * @version January 5, 2020, 8:47 am EST
 *
 * @property string tipo_obra
 */
class TipoObras extends Model
{
    use SoftDeletes;

    public $table = 'tipo_obras';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'tipo_obra',
        'coeficienteConstante'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'tipo_obra' => 'string',
        'coeficienteConstante' => 'float'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'tipo_obra' => 'required',
        'coeficienteConstante' => 'required'
    ];

}

app/Http/Controllers/TipoObrasController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTipoObrasRequest;
use App\Http\Requests\UpdateTipoObrasRequest;
use App\Repositories\TipoObrasRepository;
use App\Http\Controllers\AppBaseController;
use function Couchbase\defaultDecoder;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class TipoObrasController extends AppBaseController
{
    /** @var  TipoObrasRepository */
    private $tipoObrasRepository;

    public function __construct(TipoObrasRepository $tipoObrasRepo)
    {
        $this->tipoObrasRepository = $tipoObrasRepo;
    }

    /**
     * Display a listing of the TipoObras.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->tipoObrasRepository->pushCriteria(new RequestCriteria($request));
        $tipoObras = $this->tipoObrasRepository->all();

        return view('tipo_obras.index')
            ->with('tipoObras', $tipoObras);
    }

    /**
     * Show the form for creating a new TipoObras.
     *
     * @return Response
     */
    public function create()
    {
        return view('tipo_obras.create');
    }

    /**
     * Store a newly created TipoObras in storage.
     *
     * @param CreateTipoObrasRequest $request
     *
     * @return Response
     */
    public function store(CreateTipoObrasRequest $request)
    {
        $input = $request->all();

        $tipoObras = $this->tipoObrasRepository->create($input);

        Flash::success('Tipo Obras guardado satisfactoriamente.');

        return redirect(route('tipoObras.index'));
    }

    /**
     * Display the specified TipoObras.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tipoObras = $this->tipoObrasRepository->findWithoutFail($id);

        if (empty($tipoObras)) {
            Flash::error('Tipo Obras not found');

            return redirect(route('tipoObras.index'));
        }

        return view('tipo_obras.show')->with('tipoObras', $tipoObras);
    }

    /**
     * Show the form for editing the specified TipoObras.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tipoObras = $this->tipoObrasRepository->findWithoutFail($id);

        if (empty($tipoObras)) {
            Flash::error('Tipo Obras not found');

            return redirect(route('tipoObras.index'));
        }

        return view('tipo_obras.edit')->with('tipoObras', $tipoObras);
    }

    /**
     * Update the specified TipoObras in storage.
     *
     * @param  int              $id
     * @param UpdateTipoObrasRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTipoObrasRequest $request)
    {
        $tipoObras = $this->tipoObrasRepository->findWithoutFail($id);

        if (empty($tipoObras)) {
            Flash::error('Tipo Obras not found');

            return redirect(route('tipoObras.index'));
        }

        $tipoObras = $this->tipoObrasRepository->update($request->all(), $id);

        Flash::success('Tipo Obras guardado satisfactoriamente.');

        return redirect(route('tipoObras.index'));
    }

    /**
     * Remove the specified TipoObras from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tipoObras = $this->tipoObrasRepository->findWithoutFail($id);

        if (empty($tipoObras)) {
            Flash::error('Tipo Obras not found');

            return redirect(route('tipoObras.index'));
        }

        $this->tipoObrasRepository->delete($id);

        Flash::success('Tipo Obras eliminado satisfactoriamente.');

        return redirect(route('tipoObras.index'));
    }
}

resources/views/tipo_obras/create.blade.php
@extends('layouts.app')
@section('nombre_modulo', 'Tipo Obras')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">Inicio</a></li>
    <li class="breadcrumb-item">Configuración</li>
    <li class="breadcrumb-item"><a href="{{route('tipoObras.index')}}">Tipo Obras</a></li>
    <li class="breadcrumb-item active"><a href="{{route('tipoObras.create')}}">Crear Tipo de Obra</a></li>
@endsection

@section('content')
    <section class="content-header">
        <h1>
            <i class="fas fa-campground"></i>
            Tipo de Obra
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'tipoObras.store', 'class'=>'w-100']) !!}

                        @include('tipo_obras.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tipo_obras/edit.blade.php
@extends('layouts.app')
@section('nombre_modulo', 'Tipo Obras')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">Inicio</a></li>
    <li class="breadcrumb-item">Configuración</li>
    <li class="breadcrumb-item"><a href="{{route('tipoObras.index')}}">Tipo Obras</a></li>
    <li class="breadcrumb-item active">Editar Tipo Obras</li>
@endsection

@section('content')
    <section class="content-header">
        <h1>
            <i class="fas fa-user-tie"></i>
            Tipo de Obra# <b>{{str_pad($tipoObras->id, 6, '0', STR_PAD_LEFT)}}</b>
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($tipoObras, ['route' => ['tipoObras.update', $tipoObras->id], 'class'=>'w-100', 'method' => 'patch']) !!}

                        @include('tipo_obras.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/tipo_obras/fields.blade.php
<div class="row">
    <div class="col-sm-6">
        <!-- Tipo Obra Field -->
            {!! Form::label('tipo_obra', 'Tipo Obra:') !!}
            {!! Form::text('tipo_obra', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-sm-6">
            {!! Form::label('coeficienteConstante', 'Coeficiente Constante:') !!}
            {!! Form::text('coeficienteConstante', null, ['class' => 'form-control']) !!}
    </div>

</div>

<hr>
<div class="row float-right">
    <!-- Submit Field -->
    <div class="col-sm-12">
        {!! Form::submit('Guardar', ['class' => 'btn btn-success']) !!}
        <a href="{{ route('tipoObras.index') }}" class="btn btn-success">Cancelar</a>
    </div>

</div>

resources/views/tipo_obras/index.blade.php
@extends('layouts.app')
@section('nombre_modulo', 'Tipos de Obra')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">Inicio</a></li>
    <li class="breadcrumb-item">Configuración</li>
    <li class="breadcrumb-item active"><a href="{{route('tipoObras.index')}}">Tipos de Obra</a></li>
@endsection

@section('content')
    <section class="content-header">
        <h1>
            <i class="fas fa-campground"></i>
            Tipos de Obra
            @can('tipoObras.create')
                <a href="{{route('tipoObras.create')}}" class="btn btn-outline-success float-right"> <i class="fas fa-plus"></i> Crear</a>
            @endcan
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('tipo_obras.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/tipo_obras/show.blade.php
@extends('layouts.app')
@section('nombre_modulo', 'Tipo Obras')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">Inicio</a></li>
    <li class="breadcrumb-item">Configuración</li>
    <li class="breadcrumb-item"><a href="{{route('tipoObras.index')}}">Tipo Obras</a></li>
    <li class="breadcrumb-item active">Tipo de Obra</li>
@endsection

@section('content')
    <section class="content-header">
        <h1>
            <i class="fas fa-user-tie"></i>
            Tipo de Obra# <b>{{str_pad($tipoObras->id, 6, '0', STR_PAD_LEFT)}}</b>
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="col-sm-12">
                    @include('tipo_obras.show_fields')
                    <hr>
                    <div class="row float-right">
                        <div class="col-sm-12">
                            <a href="{{ route('tipoObras.index') }}" class="btn btn-success">Regresar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tipo_obras/show_fields.blade.php
<!-- Tipo Obra Field -->
<div class="form-group">
    <b>{!! Form::label('tipo_obra', 'Tipo Obra:') !!}</b>
    <p>{{ $tipoObras->tipo_obra }}</p>
</div>

<!-- Tipo Obra Field -->
<div class="form-group">
    <b>{!! Form::label('tipo_obra', 'Coeficiente Constante:') !!}</b>
    <p>{{ $tipoObras->coeficiente }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    <b>{!! Form::label('created_at', 'Created At:') !!}</b>
    <p>{{ $tipoObras->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    <b>{!! Form::label('updated_at', 'Updated At:') !!}</b>
    <p>{{ $tipoObras->updated_at }}</p>
</div>

resources/views/tipo_obras/table.blade.php
@section('css')
    <link rel="stylesheet" href="{{asset('vendor/wrappixel/material-pro/4.2.1/assets/plugins/datatables/datatables.min.css')}}">
@endsection

<div class="table-responsive">
    <table class="table" id="data-table">
        <thead>
            <tr>
                <th>Tipo Obra</th>
                <th>Coeficiente Constante</th>
                <th>Acción</th>
            </tr>
        </thead>
        <tbody>
        @foreach($tipoObras as $tipoObras)
            <tr>
                <td>{{ $tipoObras->tipo_obra }}</td>
                <td>{{ $tipoObras->coeficiente }}</td>
                <td class="td-actions text-center">
                    @can('tipoObras.show')
                        <a href="{{ route('tipoObras.show', [$tipoObras->id]) }}" class="btn btn-outline-success btn-round btn-sm">
                            <i class="fas fa-eye"></i>
                        </a>
                    @endcan
                    @can('tipoObras.edit')
                        <a href="{{ route('tipoObras.edit', [$tipoObras->id]) }}" class="btn btn-outline-success btn-round btn-sm">
                            <i class="fas fa-edit"></i>
                        </a>
                    @endcan
                    @can('tipoObras.destroy')
                        {!! Form::open(['route' => ['tipoObras.destroy', $tipoObras->id], 'method' => 'DELETE','id' => 'formDelete','class' => 'd-inline']) !!}
                        <button class="btn btn-outline-success btn-round btn-sm">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                        {!! Form::close() !!}
                    @endcan
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

@section('js')

    <script src="{{asset('vendor/wrappixel/material-pro/4.2.1/assets/plugins/datatables/datatables.min.js')}}"></script>
    <script src="{{asset('js/data_tables_index.js')}}"></script>

@endsection