routes/web.php
<?php
#-------------------------------------
#RUTAS PUBLICAS
#-------------------------------------
Auth::routes(['verify' => true]);

#Login y Deslogueo
Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login.post');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('logout', 'Auth\LoginController@logout');

#Registro de Usuario
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

# Password Reset
Route::get('password/reset', ['as' => 'password.reset', 'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm']);
Route::post('password/email', ['as' => 'password.email', 'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail']);
Route::get('password/reset/{token}', ['as' => 'password.reset.token', 'uses' => 'Auth\ResetPasswordController@showResetForm']);
Route::post('password/reset', ['as' => 'password.reset.post', 'uses' => 'Auth\ResetPasswordController@reset']);

#Socialite o Socialogin
//Route::get('login/facebook', 'SocialiteController@redirectToProvider')->name('login.facebook');
//Route::get('login/facebook/callback', 'SocialiteController@handleProviderCallback');
//
//Route::get('login/twitter', 'SocialiteController@redirectToTwitterProvider')->name('login.twitter');
//Route::get('login/twitter/callback', 'SocialiteController@handleTwitterProviderCallback');
//
//Route::get('login/google', 'SocialiteController@redirectToGoogleProvider')->name('login.google');
//Route::get('login/google/callback', 'SocialiteController@handleGoogleProviderCallback');

#Geografico
Route::get('searchState/{pais_id}', 'EstadoController@searchState')->name('searchState');
Route::get('searchCity/{estado_id}', 'CiudadController@searchCity')->name('searchCity');

#Buscar Vendedores
Route::get('searchVendedores/{cliente_id}', 'VendedorController@searchVendedores')->name('searchVendedores');

#Buscar Datos de un Servicio
Route::get('searchServicio/{servicio_id}', 'TiposController@searchServicio')->name('searchServicio');


#--------------------------------------------------------------------------------------
#RUTAS PROTEGIDAS POR LA AUTENTICACION Y VERIFICACION DE EMAIL AL MOMENTO DEL REGISTRO
#--------------------------------------------------------------------------------------

Route::group(['middleware' => array('auth', 'verified')], function () {

    #Home
    Route::get('/dashboard', 'HomeController@dashboard')->name('home-one');

    #Rutas del Perfil
    Route::get('/perfil', 'HomeController@perfil')->name('perfil');
    Route::post('/storeperfil', 'HomeController@storeperfil')->name('storeperfil');

    #Roles
    Route::resource('roles', 'RoleController');

    #Menus
    Route::resource('menus', 'MenuController');

    #Permisos
    Route::resource('permissions', 'PermissionController');

    #Usuarios
    Route::resource('users', 'UserController');
    Route::post('users/{user}', 'UserController@cambioClave')->name('users.cambioClave');

    #Paypal
    Route::get('payment/{pricing_id}', 'PaypalController@postPayment')->name('payment');
    Route::get('payment/status/{pricing_id}', 'PaypalController@getPaymentStatus')->name('payment.status');
    Route::get('pagado/{credito_id}', 'PaypalController@pagado')->name('pagado');

    #Tipos de Servicio
    Route::resource('tipos', 'TiposController');

    #Vendedores
    Route::resource('vendedors', 'VendedorController');

    #Clientes
    Route::resource('clientes', 'ClientesController');
    Route::get('estadoFinanciero', 'ClientesController@estadoFinanciero')->name('estadoFinanciero');

    #Solicitudes
    Route::resource('solicitudes', 'SolicitudesController');

    #Tipo de Obras
    Route::resource('tipoObras', 'TipoObrasController');

    #Ordenes de Trabajo
    Route::resource('ordenes', 'OrdenesController');

    Route::resource('productos', 'ProductosController');
    Route::get('searchProductosXCategoria', 'ProductosController@searchProductosXCategoria')->name('searchProductosXCategoria');

    Route::resource('productosCategorias', 'ProductosCategoriasController');

    Route::resource('subOrden', 'SubOrdenController');
    Route::get('subOrden/listar/{orden_id}', 'SubOrdenController@listar')->name('subOrden.listar');
    Route::get('subOrden/{orden_id}', 'SubOrdenController@show')->name('subOrden.show');
    Route::get('searchXfechaXcliente/{cliente}', 'SubOrdenController@searchXfechaXcliente')->name('searchXfechaXcliente');
    Route::get('searchXfechaXclienteSinVencer/{cliente}', 'SubOrdenController@searchXfechaXclienteSinVencer')->name('searchXfechaXclienteSinVencer');
    Route::get('agenda', 'SubOrdenController@agenda')->name('agenda');
    Route::get('miagenda', 'SubOrdenController@miagenda')->name('miagenda');
    Route::get('searchAgenda/{selectMes}/{tipoId}', 'SubOrdenController@searchAgenda')->name('searchAgenda');
    Route::get('searchMyAgenda/{selectMes}/{tipoId}', 'SubOrdenController@searchMyAgenda')->name('searchMyAgenda');
    Route::get('reclamos', 'SubOrdenController@reclamos')->name('reclamos');
    Route::get('vencimientos', 'SubOrdenController@vencimientos')->name('vencimientos');

    Route::resource('subOrdenDetalle', 'SubOrdenDetalleController');


    Route::resource('autos', 'AutosController');

    Route::resource('cajas', 'CajasController');

    Route::resource('cajasProductos', 'CajasProductosController');

    Route::resource('recibos', 'RecibosController');

    Route::resource('seguimiento', 'SeguimientoController');

    Route::resource('herramientas', 'HerramientasController');

    Route::resource('convenios', 'ConveniosController');

    Route::resource('adicionalesEficiencias', 'AdicionalesEficienciaController');
    Route::get('adicionalesEficiencia', 'AdicionalesEficienciaController@adicionalesEficiencia')->name('adicionalesEficiencia');
    Route::post('guardarAdicionales', 'AdicionalesEficienciaController@guardarAdicionales')->name('guardarAdicionales');

    Route::resource('adicionalesChofers', 'AdicionalesChoferController');
    Route::get('adicionalesChofer', 'AdicionalesChoferController@adicionalesChofer')->name('adicionalesChofer');
    Route::post('guardarChofer', 'AdicionalesChoferController@guardarChofer')->name('guardarChofer');

    Route::resource('seguimientos', 'SeguimientoController');

    Route::resource('ingresosEgresos', 'IngresosEgresosController');
    Route::get('proyeccion', 'IngresosEgresosController@proyeccion')->name('proyeccion');


    /*damian */
    Route::get('mysuborders', 'SubOrdenController@mysuborders')->name('mysuborders');
    Route::get('llegadasalida', 'SeguimientoController@llegadasalida')->name('llegadasalida');
    Route::get('productividad', 'SubOrdenController@productividad')->name('productividad');
    Route::get('cuentacorriente', 'ClientesController@cuentacorriente')->name('cuentacorriente');
    Route::get('limitesfinanciacion', 'ClientesController@limitepropio')->name('limitesfinanciacion');


    Route::get('liquidar', 'LiquidacionController@liquidar')->name('rrhh.liquidar');
    Route::post('liquidacion', 'LiquidacionController@liquidacion')->name('liquidacion');
    Route::post('storeLiquidacion', 'LiquidacionController@storeLiquidacion')->name('storeLiquidacion');
    Route::resource('liquidaciones', 'LiquidacionesController');

    Route::get('clientevencimientos')->name('clientevencimientos');
    Route::get('listaprecios')->name('listaprecios');
    Route::get('###')->name('###');
    Route::get('####')->name('####');
//    Route::get('notificaciones', function(){ return "Proximamente";})->name('notificaciones');
    Route::resource('notificaciones', 'NotificacionesController');
//    Route::get('liquidacion', function(){ return "Proximamente";})->name('liquidacion');

    #Prestamos
    Route::resource('prestamos', 'PrestamosController');
});

#Correo no se quedo dormido
Route::get('nodormido/{id}', 'UserController@dormido')->name('user-dormido');



Route::resource('notificacionUsers', 'NotificacionUserController');


Route::resource('statuses', 'StatusController');



Route::resource('feriados', 'FeriadoController');


Route::resource('barrios', 'BarriosController');

app/Http/Controllers/OrdenesController.php
<?php

namespace App\Http\Controllers;

use App\Estado;
use App\Http\Requests\CreateOrdenesRequest;
use App\Http\Requests\UpdateOrdenesRequest;
use App\Models\Autos;
use App\Models\Barrios;
use App\Models\Clientes;
use App\Models\Ordenes;
use App\Models\OrdenesArchivos;
use App\Models\OrdenesDetalles;
use App\Models\ProductosCategorias;
use App\Models\Solicitudes;
use App\Models\TipoObras;
use App\Models\TipoMedicion;
use App\Models\Tipos;
use App\Repositories\OrdenesRepository;
use App\Http\Controllers\AppBaseController;
use App\User;
use Illuminate\Http\Request;
use Flash;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use Carbon\Carbon;
use Mapper;

class OrdenesController extends AppBaseController
{
    /** @var  OrdenesRepository */
    private $ordenesRepository;

    public function __construct(OrdenesRepository $ordenesRepo)
    {
        $this->ordenesRepository = $ordenesRepo;
    }

    /**
     * Display a listing of the Ordenes.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->ordenesRepository->pushCriteria(new RequestCriteria($request));
        $ordenes = Ordenes::orderBy('id', 'DESC')->get();
        $tipos = Tipos::orderBy('tipo', 'asc')->get();

        return view('ordenes.index', compact('tipos'))
            ->with('ordenes', $ordenes);
    }

    /**
     * Show the form for creating a new Ordenes.
     *
     * @return Response
     */
    public function create()
    {
        $autos = Autos::orderBy('autos', 'ASC')->get();
        $clientes = Clientes::orderBy('cliente', 'asc')->get();
        $tipo_obras = TipoObras::orderBy('tipo_obra', 'asc')->get();
        $provincias = Estado::where('country_id', 10)->orderBy('name', 'asc')->get();
        $barrios = Barrios::all();
//        Mapper::map(52.381128999999990000, 0.470085000000040000)->marker(53.381128999999990000, -1.470085000000040000, ['markers' => ['symbol' => 'circle', 'scale' => 1000, 'animation' => 'DROP']]);
////        Mapper::marker(53.381128999999990000, -1.470085000000040000, ['draggable' => true, 'eventClick' => 'console.log("left click");']);
//
//        Mapper::marker(53.381128999999990000, -1.470085000000040000);
//        Mapper::marker(53.381128999999990000, -1.470085000000040000, ['animation' => 'DROP', 'label' => 'Marker', 'title' => 'Marker', 'draggable' => true]);
//        Mapper::marker(53.381128999999990000, -1.470085000000040000, ['icon' => 'https://chart.googleapis.com/chart?chst=d_map_pin_letter&chld=|FE6256|000000']);
//        Mapper::marker(53.381128999999990000, -1.470085000000040000, ['icon' => ['url' => 'https://chart.googleapis.com/chart?chst=d_map_pin_letter&chld=|FE6256|000000', 'scale' => 100]]);
//        Mapper::map(52.381128999999990000, 0.470085000000040000, ['markers' => ['icon' => ['symbol' => 'CIRCLE', 'scale' => 10], 'animation' => 'DROP', 'label' => 'Marker', 'title' => 'Marker']])->marker(53.381128999999990000, -1.470085000000040000);
//        Mapper::marker(53.381128999999990000, -1.470085000000040000, [
//            'title' 	=> 'title',
//            'icon'      => [
//                'path'         => 'M10.5,0C4.7,0,0,4.7,0,10.5c0,10.2,9.8,19,10.2,19.4c0.1,0.1,0.2,0.1,0.3,0.1s0.2,0,0.3-0.1C11.2,29.5,21,20.7,21,10.5 C21,4.7,16.3,0,10.5,0z M10.5,5c3,0,5.5,2.5,5.5,5.5S13.5,16,10.5,16S5,13.5,5,10.5S7.5,5,10.5,5z',
//                'fillColor'    => '#DD716C',
//                'fillOpacity'  => 1,
//                'strokeWeight' => 0,
//                'anchor'       => [0, 0],
//                'origin'       => [0, 0],
//                'size'         => [21, 30]
//            ],
//            'label'     => [
//                'text' => 'Marker',
//                'color' => '#B9B9B9',
//                'fontFamily' => 'Arial',
//                'fontSize' => '13px',
//                'fontWeight' => 'bold',
//            ],
//            'autoClose' => true,
//            'clickable' => false,
//            'cursor' => 'default',
//            'opacity' => 0.5,
//            'visible' => true,
//            'zIndex' => 1000,
//        ]);


        return view('ordenes.create', compact('clientes', 'tipo_obras', 'provincias', 'autos', 'barrios'));
    }

    /**
     * Store a newly created Ordenes in storage.
     *
     * @param CreateOrdenesRequest $request
     *
     * @return Response
     */
    public function store(CreateOrdenesRequest $request)
    {
        $input = $request->all();
        $input['user_create_id'] = Auth::user()->id;

        $orden = $this->ordenesRepository->create($input);

        //    SUBIR ARCHIVO FACTURA
        $files = $request->file('file');
        if(isset($files) and $files!='') {
            foreach ($files as $key => $file) {
                if (!empty($file)) {

                    $extension = explode('.', $file->getClientOriginalName());
                    $extension = end($extension);

                    $filename = "Documentacion_Orden_" . $orden->id . '_F' . date('Ymd') . '_H' . date('His') . '_' . rand(1000, 9999) . '.' . $extension;
                    \File::put('files/documentacion/' . $filename, \File::get($file));
                }

                OrdenesArchivos::create([
                    'orden_id' => $orden->id,
                    'archivo' => $filename,
                ]);
            }
        }
        Flash::success('Orden Generada satisfactoriamente.');

        return redirect(route('ordenes.index'));
    }

    /**
     * Display the specified Ordenes.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ordenes = $this->ordenesRepository->findWithoutFail($id);

        if (empty($ordenes)) {
            Flash::error('Ordenes not found');

            return redirect(route('ordenes.index'));
        }

        return view('ordenes.show')->with('ordenes', $ordenes);
    }

    /**
     * Show the form for editing the specified Ordenes.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {

        $ordenes = $this->ordenesRepository->findWithoutFail($id);
        $autos = Autos::orderBy('autos', 'ASC')->get();
        $clientes = Clientes::orderBy('cliente', 'asc')->get();
        $tipo_obras = TipoObras::orderBy('tipo_obra', 'asc')->get();
        $provincias = Estado::where('country_id', 10)->orderBy('name', 'asc')->get();
        $barrios = Barrios::all();

        if (empty($ordenes)) {
            Flash::error('Ordenes not found');

            return redirect(route('ordenes.index'));
        }

        return view('ordenes.edit', compact('ordenes', 'clientes', 'tipo_obras', 'provincias', 'autos', 'barrios'));
    }

    /**
     * Update the specified Ordenes in storage.
     *
     * @param  int $id
     * @param UpdateOrdenesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrdenesRequest $request)
    {
        $ordenes = $this->ordenesRepository->findWithoutFail($id);

        if (empty($ordenes)) {
            Flash::error('Ordenes not found');

            return redirect(route('ordenes.index'));
        }

        $input = $request->all();

        if (isset($input['fecha_verificacion'])) {
            $fecha_verificacionDT = Carbon::createFromFormat('d/m/Y', $input['fecha_verificacion']);
            $input['fecha_verificacion'] = $fecha_verificacionDT->format('Y-m-d');
        }
        if (isset($input['fecha_inicio_obra'])) {
            $fecha_hora_inicioDT = Carbon::createFromFormat('d/m/Y - H:i', $input['fecha_inicio_obra']);
            $input['fecha_inicio_obra'] = $fecha_hora_inicioDT->format('Y-m-d');
            $input['hora_inicio'] = $fecha_hora_inicioDT->format('H:i');
        }
        if (isset($input['fecha_medicion'])) {
            $fecha_medicionDT = Carbon::createFromFormat('d/m/Y', $input['fecha_medicion']);
            $input['fecha_medicion'] = $fecha_medicionDT->format('Y-m-d');
        }

        $this->ordenesRepository->update($input, $id);

        Flash::success('Orden de Trabajo guardada satisfactoriamente.');

        return redirect(route('ordenes.index'));
    }

    /**
     * Remove the specified Ordenes from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ordenes = $this->ordenesRepository->findWithoutFail($id);

        if (empty($ordenes)) {
            Flash::error('Ordenes not found');

            return redirect(route('ordenes.index'));
        }

        $this->ordenesRepository->delete($id);

        Flash::success('Orden de Trabajo eliminada satisfactoriamente.');

        return redirect(route('ordenes.index'));
    }
}

resources/views/ordenes/create.blade.php
@extends('layouts.app')
@section('nombre_modulo', 'Orden de Trabajo')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">Inicio</a></li>
    <li class="breadcrumb-item"><a href="{{route('ordenes.index')}}">Ordenes de Trabajo</a></li>
    <li class="breadcrumb-item active"><a href="{{route('ordenes.index')}}">Crear una Orden de Trabajo </a></li>
@endsection

@section('content')
    <section class="content-header">
        <h1>
            <i class="far fa-newspaper"></i>
            Crear una Orden de Trabajo
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'ordenes.store', 'class'=>'w-100', 'files' => true]) !!}
                            @include('ordenes.form')
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/ordenes/edit.blade.php
@extends('layouts.app')
@section('nombre_modulo', 'Orden de Trabajo')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">Inicio</a></li>
    <li class="breadcrumb-item"><a href="{{route('ordenes.index')}}">Ordenes de Trabajo</a></li>
    <li class="breadcrumb-item active"><a href="{{route('ordenes.index')}}">Editar una Orden de Trabajo </a></li>
@endsection

@section('content')
    <section class="content-header">
        <h1>
            <i class="far fa-newspaper"></i>
            Orden de Trabajo# <b>{{$codOrden=str_pad($ordenes->id, 6, '0', STR_PAD_LEFT)}}</b>
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ordenes, ['route' => ['ordenes.update', $ordenes->id], 'class'=>'w-100', 'method' => 'patch']) !!}
                   @include('ordenes.form')
                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/ordenes/index.blade.php
@extends('layouts.app')
@section('nombre_modulo', 'Orden de Trabajo')
@section('breadcrumb')
    <li class="breadcrumb-item"><a href="{{route('home-one')}}">Inicio</a></li>
    <li class="breadcrumb-item active"><a href="{{route('ordenes.index')}}">Ordenes de Trabajo</a></li>
@endsection

@section('content')
    <section class="content-header">
        <h1>
            <i class="far fa-newspaper"></i>
            Ordenes de Trabajo
            @can('ordenes.create')
                <a href="{{route('ordenes.create')}}" class="btn btn-outline-success float-right">
                    <i class="fas fa-plus"></i>
                    Crear Orden de Trabajo
                </a>
            @endcan
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('ordenes.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/ordenes/modalFotos.blade.php
<!--    MODAL TOMAR FILE-->
<div class="modal fade" tabindex="-1" role="dialog" id="ModalFiles">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-light">
                <h5>Subir Archivo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    <i class="far fa-times-circle"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive-md">
                            <table class="table table-striped table-bordered" id="tableFiles">
                                <tbody>
                                <tr></tr>
                                <tr>
                                    <td>
                                        <input type="file" name="file[]" class="form-control pb-5">
                                    </td>
                                    <td style="vertical-align: middle">
                                        <button class="btn btn-outline-danger btn-sm btnDelFile" type="button">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 text-center">
                        <input type="hidden" id="contadorFile" name="contadorFile" value="1">
                        <button class="btn btn-primary btn-sm" type="button" id="btnAddFile">Agregar Otro Archivo</button>
                        <button class="btn btn-primary btn-sm" type="button" data-dismiss="modal">Terminar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/ordenes/modalTipo.blade.php
<!--/*************************************************************
**      MODAL Documento                                     **
**************************************************************/-->
<div id="ModalTipo" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <form action="{{route('subOrden.create')}}" method="get" name="formTipo" id="formTipo" autocomplete="off">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title">Tipo de Sub Orden de Trabajo</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">
                    <div class="container">
                        @foreach($tipos AS $tipo)
                            <div class="row">
                                <label class="custom-control custom-radio">
                                    <input id="tipos_id{{$tipo->id}}" name="tipos_id" type="radio" class="custom-control-input" value="{{$tipo->id}}">
                                    <span class="custom-control-label">{{$tipo->tipo}}</span>
                                </label>
                            </div>
                        @endforeach
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="idOrden" id="idOrden" value="">
                    <button type="submit" class="btn btn-success waves-effect text-left">Siguiente</button>
                    <button type="button" class="btn btn-success waves-effect text-left" data-dismiss="modal">Cancelar</button>
                </div>
            </div>
        </form>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!--************************************************************-->